version: "3.8"

services:
  api:
    network_mode: host
    container_name: api
    image: craw2/api
    build:
      network: host
      context: ./api
    volumes:
      - ./api:/app/src
  ui:
    network_mode: host
    container_name: ui
    image: craw2/ui
    build:
      network: host
      context: ./ui
    volumes:
      - ./ui/src:/app/src
  publisher:
    network_mode: host
    container_name: pub
    image: craw/pub
    build:
      network: host
      context: ./publisher
    volumes:
      - ./publisher/src:/app/src
      - ./publisher/dist:/publisher/dist